# NumPy Tutorial
Thanks to **[codebasics](https://www.youtube.com/channel/UCh9nVJoWXmFb7sLApWGcLPQ)** for providing this tutorial. You may find the source video [here](https://youtu.be/a8aDcLk4vRc).

In [1]:
import numpy as np

In [7]:
a = np.array([5, 6, 9]) # creates a numpy array

In [8]:
a[0]

5

In [9]:
a[1]

6

In [10]:
a.ndim

1

In [11]:
a = np.array([[1, 2], [3, 4], [5, 6]])
a.ndim # returns the dimension of the numpy array

2

In [15]:
a.itemsize # returns the size of each element of an array in bytes

8

In [16]:
a.dtype

dtype('int64')

In [17]:
a = np.array([[1, 2], [3, 4], [5, 6]], dtype = np.float64)

In [18]:
a.itemsize

8

In [19]:
a.dtype

dtype('float64')

In [20]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [22]:
a.size # returns total number of elements in the array

6

In [23]:
a.shape # returns shape of a numpy array

(3, 2)

In [24]:
a = np.array([[1, 2], [3, 4], [5, 6]], dtype = complex)

In [25]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [26]:
a.itemsize

16

In [27]:
a.dtype

dtype('complex128')

In [28]:
np.zeros((3, 4)) # creates a numpy array of zeros of shape 3 x 4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
np.arange(1, 5) # analogous to range function, creates a numpy array of the elements

array([1, 2, 3, 4])

In [31]:
np.arange(1, 5, 2)

array([1, 3])

In [32]:
np.linspace(1, 5, 10) # generates 10 numbers between 1 and 5 (included), linearly spaced 

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [33]:
np.linspace(1, 5, 5)

array([1., 2., 3., 4., 5.])

In [35]:
a = np.array([[1, 2], [3, 4], [5, 6]])

In [36]:
a.shape

(3, 2)

In [37]:
a.reshape(2, 3) # reshapes the array into the shape specified

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
a.reshape(6, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [40]:
a.ravel() # flattens the numpy array to one dimension, does not change the array itself 

array([1, 2, 3, 4, 5, 6])

In [41]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
a.min() # returns minimum element in the array

1

In [43]:
a.max() # returns largest element in the array

6

In [44]:
a.sum() # returns the sum of all elements in the array

21

In [45]:
a.sum(axis = 0) # axis: 0 for columns, 1 for rows ==> 0 will add all elements in the respective columns

array([ 9, 12])

In [46]:
a.sum(axis = 1) # adds all the elements in each row

array([ 3,  7, 11])

In [49]:
np.sqrt(a) # computes square root of each element in the array

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [50]:
np.std(a) # computes standard deviation

1.707825127659933

In [53]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [54]:
b = np.array([[5, 6], [7, 8]])
b

array([[5, 6],
       [7, 8]])

In [55]:
a + b # element wise operations

array([[ 6,  8],
       [10, 12]])

In [56]:
a - b

array([[-4, -4],
       [-4, -4]])

In [57]:
a * b

array([[ 5, 12],
       [21, 32]])

In [58]:
a / b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [59]:
a.dot(b) # gives matrix product of the matrices

array([[19, 22],
       [43, 50]])

In [62]:
np.dot(a, b) # alternate way

array([[19, 22],
       [43, 50]])